name: Save Data from Participants

on:
  repository_dispatch:
    types: [save-coordinates]

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Save data to CSV
        run: |
          python save_data.py

      - name: Commit data and push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'data/'
          message: 'Add new participant data'
          author_name: 'your-username'
          author_email: 'your-email@example.com'
          token: ${{ secrets.MY_TOKEN }}
